version: '3.8'
services:
  api:
    user: 1000:1000
    build: .
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    
  db:
    image: postgres:16rc1-alpine3.17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - db:/var/lib/postgressql/data 
volumes:
  db:
