version: '3.8'
services:
  api:
    user: 1000:1000
    build: .
    ports:
      - 4000:4000
    env_file: .env
    command: sh -c "npm install && npm run dev"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - db:/var/lib/postgressql/data 
volumes:
  db:
